apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: keycloak-letsencrypt
  namespace: istio-system
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: eltonmmoreira@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: keycloak-letsencrypt
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            class: istio