apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
type: Opaque
data:
  username: cG9zdGdyZXM=      # required field for kubernetes.io/basic-auth
  password: dGVzdHBhc3N3b3Jk