apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: keycloak-kustomization
resources:
  - namespace.yaml
  - postgres.yaml
  - keycloak-db-secret.yaml
  - cluster-issuer-keycloak.yaml
  - keycloak-certificate.yaml
  - keycloak-gateway.yaml
  - keycloak-virtual-service.yaml