apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert-site
  namespace: istio-system
spec:
  secretName: ingress-cert-site
  issuerRef:
    name: letsencrypt-site
    kind: ClusterIssuer
  commonName: fluytcloud.com
  dnsNames:
    - fluytcloud.com
